Repository Team-Haruchi/HARUCHI_iOS, pull requests merged in 2024-08, with the labels that each got.

#57 [Feat] Cancel membership UI
  HARUCHI/HARUCHI.xcodeproj/project.pbxproj
  HARUCHI/HARUCHI/App/ContentView.swift
  HARUCHI/HARUCHI/App/Detail/CancelMembershipView.swift
  HARUCHI/HARUCHI/App/Detail/DetailMainView.swift
  HARUCHI/HARUCHI/App/Detail/MemberInfo.swift
  HARUCHI/HARUCHI/App/HARUCHIApp.swift
  HARUCHI/HARUCHI/Assets.xcassets/CancelMember/Contents.json
  HARUCHI/HARUCHI/Assets.xcassets/CancelMember/cancelMember_caution.imageset/Contents.json
  HARUCHI/HARUCHI/Assets.xcassets/CancelMember/cancelMember_caution.imageset/Vector.png
  HARUCHI/HARUCHI/Assets.xcassets/CancelMember/cancelMember_checked.imageset/Contents.json
  HARUCHI/HARUCHI/Assets.xcassets/CancelMember/cancelMember_checked.imageset/Vector (2).png
  HARUCHI/HARUCHI/Assets.xcassets/CancelMember/cancelMember_unchecked.imageset/Contents.json
  HARUCHI/HARUCHI/Assets.xcassets/CancelMember/cancelMember_unchecked.imageset/Vector (1).png
Labels: feature

#59 [Feat] HomeMainView Weekcalender
  HARUCHI/HARUCHI.xcodeproj/project.pbxproj
  HARUCHI/HARUCHI/App/Home/HomeMainView.swift
  HARUCHI/HARUCHI/App/Home/HomeReceiptView.swift
  HARUCHI/HARUCHI/App/Home/HomeSpendView.swift
  HARUCHI/HARUCHI/App/Home/HomeViewModel.swift
  HARUCHI/HARUCHI/App/Onboarding/OnboardingViewModel.swift
  HARUCHI/HARUCHI/Assets.xcassets/Home/HomeClock.imageset/Contents.json
  HARUCHI/HARUCHI/Assets.xcassets/Home/HomeClock.imageset/HomeClock.png
  HARUCHI/HARUCHI/Assets.xcassets/Home/HomeCoin.imageset/Contents.json
  HARUCHI/HARUCHI/Assets.xcassets/Home/HomeCoin.imageset/HomeCoin.png
  HARUCHI/HARUCHI/Components/WeekCalendar/WeekCalendarModel.swift
  HARUCHI/HARUCHI/Components/WeekCalendar/WeekCalendarView.swift
  HARUCHI/HARUCHI/Components/WeekCalendar/WeekCalendarViewModel.swift
Labels: feature

#60 [Network] Login
  HARUCHI/HARUCHI.xcodeproj/project.pbxproj
  HARUCHI/HARUCHI/App/HARUCHIApp.swift
  HARUCHI/HARUCHI/App/Login/LoginView.swift
  HARUCHI/HARUCHI/App/Login/LoginViewModel.swift
  HARUCHI/HARUCHI/App/RootView.swift
  HARUCHI/HARUCHI/App/SignIn/StartView.swift
  HARUCHI/HARUCHI/Components/LoadingView.swift
  HARUCHI/HARUCHI/Info.plist
  HARUCHI/HARUCHI/Network/API/AuthAPI.swift
  HARUCHI/HARUCHI/Network/Entity/Base.swift
  HARUCHI/HARUCHI/Network/Entity/LoginResponse.swift
  HARUCHI/HARUCHI/Network/Service/APIRequestable.swift
  HARUCHI/HARUCHI/Network/Service/AuthService.swift
Labels: feature, Network

#64 [Network] MemberInfo Network
  HARUCHI/HARUCHI.xcodeproj/project.pbxproj
  HARUCHI/HARUCHI/App/Detail/DetailMainView.swift
  HARUCHI/HARUCHI/App/Detail/MemberInfo.swift
  HARUCHI/HARUCHI/App/Detail/MemberInfoViewModel.swift
  HARUCHI/HARUCHI/Network/API/MemberInfoAPI.swift
  HARUCHI/HARUCHI/Network/Entity/MemberInfoResponse.swift
  HARUCHI/HARUCHI/Network/Service/MemberInfoService.swift
Labels: Network

#65 [Network] CancelMembership
  HARUCHI/HARUCHI.xcodeproj/project.pbxproj
  HARUCHI/HARUCHI/App/Detail/CancelMembershipView.swift
  HARUCHI/HARUCHI/App/Detail/CancelMembershipViewModel.swift
  HARUCHI/HARUCHI/Network/API/CancelMembershipAPI.swift
  HARUCHI/HARUCHI/Network/Entity/CancelMembershipResponse.swift
  HARUCHI/HARUCHI/Network/Service/CancelMembershipService.swift
Labels: feature, Network

#67 [Network] finance
  HARUCHI/HARUCHI.xcodeproj/project.pbxproj
  HARUCHI/HARUCHI/App/HARUCHIApp.swift
  HARUCHI/HARUCHI/App/Home/HomeMainView.swift
  HARUCHI/HARUCHI/App/Home/HomeReceiptView.swift
  HARUCHI/HARUCHI/App/Home/HomeSpendView.swift
  HARUCHI/HARUCHI/App/Home/HomeViewModel.swift
  HARUCHI/HARUCHI/App/Onboarding/OnboardingBudgetView.swift
  HARUCHI/HARUCHI/App/Onboarding/OnboardingNicknameView.swift
  HARUCHI/HARUCHI/App/Onboarding/OnboardingViewModel.swift
  HARUCHI/HARUCHI/App/RootView.swift
  HARUCHI/HARUCHI/Assets.xcassets/Common/mainLogo.imageset/Contents.json
  HARUCHI/HARUCHI/Assets.xcassets/Home/HomeLogo.imageset/Contents.json
  HARUCHI/HARUCHI/Assets.xcassets/Home/HomeLogo.imageset/HomeLogo.png
  HARUCHI/HARUCHI/Components/WeekCalendar/WeekCalendarView.swift
  HARUCHI/HARUCHI/Network/API/ExpenditureAPI.swift
  HARUCHI/HARUCHI/Network/API/IncomeAPI.swift
  HARUCHI/HARUCHI/Network/Entity/ExpenditureResult.swift
  HARUCHI/HARUCHI/Network/Entity/IncomeResult.swift
  HARUCHI/HARUCHI/Network/Service/AuthPlugin.swift
  HARUCHI/HARUCHI/Network/Service/ExpenditureService.swift
  HARUCHI/HARUCHI/Network/Service/IncomeService.swift
Labels: feature, Network

#72 [Refactor] DetailView(version, sharing app) refactoring
  HARUCHI/HARUCHI/App/Detail/DetailMainView.swift
Labels: refactor

#70 [Network] SignIn
  HARUCHI/HARUCHI.xcodeproj/project.pbxproj
  HARUCHI/HARUCHI/App/SignIn/EmailAuthView.swift
  HARUCHI/HARUCHI/App/SignIn/SignInView.swift
  HARUCHI/HARUCHI/App/SignIn/SignInViewModel.swift
  HARUCHI/HARUCHI/Network/Entity/BaseWithOutResult.swift
  HARUCHI/HARUCHI/Network/Service/AuthService.swift
Labels: feature, Network

#75 [Refactor] Refactoring CancelMembershipView
  HARUCHI/HARUCHI.xcodeproj/project.pbxproj
  HARUCHI/HARUCHI/App/Detail/CancelMembershipView.swift
  HARUCHI/HARUCHI/App/Detail/CancelMembershipViewModel.swift
  HARUCHI/HARUCHI/Components/FinalConfirmButton.swift
Labels: refactor, feature

#77 🚑 :: Hotfix
  HARUCHI/HARUCHI.xcodeproj/project.pbxproj
  HARUCHI/HARUCHI/App/Budget/BudgetMainView.swift
  HARUCHI/HARUCHI/App/Budget/BudgetMainViewModel.swift
  HARUCHI/HARUCHI/App/HARUCHIApp.swift
  HARUCHI/HARUCHI/App/Home/HomeMainView.swift
  HARUCHI/HARUCHI/App/Home/HomeReceiptView.swift
  HARUCHI/HARUCHI/App/Home/HomeSpendView.swift
  HARUCHI/HARUCHI/App/Home/HomeViewModel.swift
  HARUCHI/HARUCHI/App/Onboarding/OnboardingBudgetView.swift
  HARUCHI/HARUCHI/App/Onboarding/OnboardingNicknameView.swift
  HARUCHI/HARUCHI/App/Onboarding/OnboardingViewModel.swift
  HARUCHI/HARUCHI/App/RootView.swift
  HARUCHI/HARUCHI/App/SignIn/EmailAuthView.swift
  HARUCHI/HARUCHI/Components/Calendar/CalendarView.swift
  HARUCHI/HARUCHI/Components/Calendar/CalendarViewModel.swift
  HARUCHI/HARUCHI/Components/WeekCalendar/WeekCalendarView.swift
  HARUCHI/HARUCHI/Network/API/BudgetAPI.swift
  HARUCHI/HARUCHI/Network/API/IncomeAPI.swift
  HARUCHI/HARUCHI/Network/Service/AuthPlugin.swift
  HARUCHI/HARUCHI/Network/Service/BudgetService.swift
  HARUCHI/HARUCHI/Network/Service/ExpenditureService.swift
  HARUCHI/HARUCHI/Network/Service/IncomeService.swift
Labels: bug

#83 [Network] Onboarding
  HARUCHI/HARUCHI.xcodeproj/project.pbxproj
  HARUCHI/HARUCHI/App/AppState.swift
  HARUCHI/HARUCHI/App/Detail/CancelMembershipView.swift
  HARUCHI/HARUCHI/App/HARUCHIApp.swift
  HARUCHI/HARUCHI/App/Login/LoginView.swift
  HARUCHI/HARUCHI/App/Login/LoginViewModel.swift
  HARUCHI/HARUCHI/App/Onboarding/OnboardingBudgetView.swift
  HARUCHI/HARUCHI/App/Onboarding/OnboardingNicknameView.swift
  HARUCHI/HARUCHI/App/Onboarding/OnboardingViewModel.swift
  HARUCHI/HARUCHI/App/RootView.swift
  HARUCHI/HARUCHI/App/SignIn/EmailAuthView.swift
  HARUCHI/HARUCHI/App/SignIn/SignInView.swift
  HARUCHI/HARUCHI/Helper/Manager/UserDefaultManager.swift
  HARUCHI/HARUCHI/Network/Service/AuthService.swift
Labels: Network

#84 [Bug] Onboarding UI
  HARUCHI/HARUCHI/App/HARUCHIApp.swift
  HARUCHI/HARUCHI/App/Onboarding/OnboardingBudgetView.swift
  HARUCHI/HARUCHI/App/Onboarding/OnboardingNicknameView.swift
  HARUCHI/HARUCHI/App/SignIn/EmailAuthView.swift
  HARUCHI/HARUCHI/App/SignIn/SignInViewModel.swift
Labels: design, refactor

#85 [Feat] HomeMainView Edit Budget
  HARUCHI/HARUCHI/App/Budget/BudgetMainView.swift
  HARUCHI/HARUCHI/App/Budget/BudgetMainViewModel.swift
  HARUCHI/HARUCHI/App/Budget/BudgetPullPushView.swift
  HARUCHI/HARUCHI/App/Home/HomeMainView.swift
  HARUCHI/HARUCHI/App/Home/HomeViewModel.swift
  HARUCHI/HARUCHI/Network/API/BudgetAPI.swift
  HARUCHI/HARUCHI/Network/Entity/BudgetResponse.swift
  HARUCHI/HARUCHI/Network/Service/BudgetService.swift
Labels: refactor, feature

#90 [Refactor] Refactoring CancelMembership
  HARUCHI/HARUCHI.xcodeproj/project.pbxproj
  HARUCHI/HARUCHI/App/Detail/CancelMembershipView.swift
Labels: refactor

#92 [Network] CancelMembership MemberInfo Network
  HARUCHI/HARUCHI/App/Detail/CancelMembershipView.swift
  HARUCHI/HARUCHI/App/Detail/DetailMainView.swift
Labels: bug, refactor, Network

#93 [Feat] Push Budget API
  HARUCHI/HARUCHI/App/Budget/BudgetMainView.swift
  HARUCHI/HARUCHI/App/Budget/BudgetMainViewModel.swift
  HARUCHI/HARUCHI/App/Budget/BudgetPullPushView.swift
  HARUCHI/HARUCHI/Components/Calendar/CalendarViewModel.swift
  HARUCHI/HARUCHI/Network/API/BudgetAPI.swift
  HARUCHI/HARUCHI/Network/Entity/BudgetResponse.swift
  HARUCHI/HARUCHI/Network/Service/BudgetService.swift
Labels: feature, Network

#96 [Network] Recepit
  HARUCHI/HARUCHI/App/Home/HomeReceiptView.swift
  HARUCHI/HARUCHI/App/Home/HomeViewModel.swift
Labels: bug

#97 [Feat] Pull Budget
  HARUCHI/HARUCHI/App/Budget/BudgetMainView.swift
  HARUCHI/HARUCHI/App/Budget/BudgetMainViewModel.swift
  HARUCHI/HARUCHI/App/Budget/BudgetPullPushView.swift
  HARUCHI/HARUCHI/App/Home/HomeMainView.swift
  HARUCHI/HARUCHI/Network/API/BudgetAPI.swift
  HARUCHI/HARUCHI/Network/Service/BudgetService.swift
Labels: feature, Network

#99 [Feat] Refreshable in BudgetView
  HARUCHI/HARUCHI/App/Budget/BudgetMainView.swift
  HARUCHI/HARUCHI/App/Budget/BudgetMainViewModel.swift
  HARUCHI/HARUCHI/App/Home/HomeReceiptView.swift
  HARUCHI/HARUCHI/App/Home/HomeViewModel.swift
  HARUCHI/HARUCHI/Network/Entity/BudgetResponse.swift
  HARUCHI/HARUCHI/Network/Service/BudgetService.swift
Labels: bug, feature

#100 Edit ReceiptView Bug
  HARUCHI/HARUCHI/App/Home/HomeMainView.swift
  HARUCHI/HARUCHI/App/Home/HomeReceiptView.swift
  HARUCHI/HARUCHI/Network/Entity/CloseResponse.swift
Labels: bug
